all:
	arm-linux-gnueabihf-gcc -static test.c -o test_static.exe
	arm-linux-gnueabihf-gcc test.c -o test.exe
	arm-linux-gnueabihf-gcc -static -g test.c -o test_static_g.exe
	arm-linux-gnueabihf-gcc -g test.c -o test_g.exe
